Модуль 3
js-tasks-ru/vue-20220125_dmitry-zakharov5 pull request #3
Opened 2022-02-02 17:11 UTC by sasukeuchiwa666

2022-02-02 17:12 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-05 11:14 UTC, ShGKme requested changes
В 01-VBindCover требуется напрямую работать с входными параметрами, либо (лучше) использовать вычисляемые свойства для поддержки обновления компонента. Также желательно убрать некорректный стиль с `url(undefiend)`.

2022-02-05 11:14 UTC, ShGKme commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
>  };
`linear-gradient(0deg, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4))` - совсем не связано с логикой работы компонента, не его данные и даже не результат вычисления от них. Это просто стили и лучше оставлять его в стилях.

2022-02-05 11:14 UTC, ShGKme commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
> +  background-image: v-bind('styles.bgGradient'), v-bind('styles.bgImage'), var(--default-cover);
Сейчас у элемента всегда три фона: градиент, возможно изображение и изображение по умолчанию. Такое решение формально работает, потому что `url(undefined)` не ломает CSS, но это некорректные стили.

У элемента всегда должно быть два фона:
1. Градиент
2. Либо `url(image)`, если изображение есть, либо `var(--default-cover)`, но не оба сразу.

2022-02-06 08:26 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-07 11:52 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-07 11:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-02-07 13:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-02-07 14:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-02-09 13:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-02-09 20:07 UTC, ShGKme requested changes
В `01-UiFormGroup1` требуется избавиться от конфликта имён в свойствах компонента.
В `03-UiDropdown1` требуется поменять `v-show` на `v-if` при выводе иконки, и добавить вычисляемые свойства для определения выбранного значения.

Остальные задачи приняты.

2022-02-09 20:07 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +      <span v-if="selected">{{ selected }}</span>
Когда по условию меняется лишь содержимое узла, лучше в шаблоне определять условием именно содержимое (тернарным оператором) или выносить это в вычисляемое свойство (для больших выражений).

С `v-if` получается копирование целиком узла, это лишнее дублирование кода узла.

2022-02-09 20:07 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +        {{ option.text }}
Директива `v-show` здесь не подходит. С ней узел всегда будут выводиться на страницу, даже когда для него нет данных (что приводит к ошибкам, в данном случае - выводе компонента иконки при отсутствии иконки). 

Здесь должна использоваться директива `v-if`, с которой ненужные узды не будут рендериться вообще. А `v-show` - для случаев, когда какой-то узел требуется то срывать, то показывать (как выше целиком список вариантов).

2022-02-09 20:07 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
`selected` и `icon` - не самостоятельные данные компонента. Это данные, которые определяются значением компонента (`modelValue`). Сейчас эти свойства обновляются при изменении `modelValue`, но изменение `options` не учтено. 

Вместо этого должно быть вычисляемое свойство.

2022-02-09 20:07 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
Тернарный оператор - это оператор, который возвращает значение 2-го или 3-го операнда в зависимости от 1-го. Его обычно используют, именно когда требуется получить значение в вычислениях/выражениях.

А здесь - обычное ветвление, лучше использовать `if / else`.

2022-02-09 20:07 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
Можно использовать метод массива some: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2022-02-14 20:22 UTC, ShGKme approved these changes
Принято, но обратите внимание на комментарии.

2022-02-14 20:22 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
Лучше не использовать время (`Date.now`) в качестве идентификатора. Не гарантируется его уникальность. Вместо времени может быть инкрементный идентификатор (просто делать `lastId++` на уровне модуля компонента), или случайный (`nanoid`, `uuid`).

2022-02-14 20:22 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/ToastList.vue
> +  },
В `data` описывается объект с реактивными данными компонента, которые определяют его состояние, которые изменяются в процессе жизни компонента, на изменение которых требуется реагировать. `toastIcon` - константа. 

Её можно описать в опциях компонента и обращаться в шаблоне через `$options`.

[https://github.com/js-tasks-ru/vue3-course-materials/blob/master/02-components/02-page-meetups/components/PageMeetups.js#L14-L18](https://github.com/js-tasks-ru/vue3-course-materials/blob/master/02-components/02-page-meetups/components/PageMeetups.js#L14-L18)

Такое разделение позволит сразу видеть, что является данными компонента, или видеть, что у компонента нет своего состояния.

2022-02-14 20:23 UTC, merged